valid_email = 'evgenjamar@mail.ru'
valid_phone = '+7(926)9390545'
valid_password = 'poland2012'
valid_login = 'evgenjamar'
valid_ls = '123456789123'
valid_username = u"Тестов Ромашка"
ad_slogan = u"Персональный помощник в цифровом мире Ростелекома"
site = 'https://b2c.passport.rt.ru'
link_lk = "/account_b2c/page"
drv_path = '../../ChromeDrv/chromedriver.exe'
